aptly-snapshot-create.yml, aptly-snapshot-merge-and-publish.yml, aptly-sync-to-mirror.yml, artifacting-vars.yml
Distribution release may not be the same as
ansible_distribution_release, if you want to build for xenial
under trusty or the opposite.
=> Use distribution_release instead of ansible_

aptly-vars.yml
To make sure we don't overload the repo server's disk capacity,
this change of vars reduce the scope of what's apt mirrored on
repo host.
This can be extended in the future.
=> Ease up for first CI testing

sync-with-mirror.yml
We ensure sync ownership only on remote node, where we should
ensure both on mirrors and on localhost.
=> Ensure sync ownership

aptly-all.yml, sync-with-mirror.yml
Because CI deletes the complete content of the artifacts folder
on a clean machine, instead of cleaning just the aptly folder.
=> Make sure the rsync doesn't crush apt keys from CI

aptly-snapshot-merge-and-publish.yml
The apt pools are separated by their publish prefix. If we use
the tag as prefix, it will keep things well separated, including
the publishing folders, which would lead to more space used.
In this commit, we move to using components instead.
A release tag will therefore appear as a component under the
dist it would use.  We are using still keeping prefixes, but
only to keep the independant (no merge snapshots) and integrated
(merged snapshots) separated.
=> Move to component instead of prefixes.

aptly-vars.yml
hwraid.le-vert.net uses the same package name, version and
architecture for two different packages (in two separate distros).
This prevents one single pool to be used for both distros.
This commit splits the apt pools.
=> Fix hwraid.le-vert.net pkg conflict

openstackgit-update.yml
This patch updates the git sync playbook to synchronise to rpc-repo
when it's complete.
=> Update openstackgit playbook to synchronise to rpc-repo

openstackgit-update.yml
Currently the destination for all clones is the same directory,
so the resulting folder only contains the last clone. This patch
corrects the task to ensure that each clone is in its own dir.
=> Correct git clone destination

aptly-all.yml, aptly-vars.yml, sync-with-mirror.yml
We need to publish the key used for signing apt packages if we
want to use apt mirror with gpgcheck (default on).
Signed-off-by: Jean-Philippe Evrard <jean-philippe.evrard@rackspace.co.uk>
=> Publish the apt key used for signing on mirror

aptly-vars.yml
The merged snapshot didn't contain le-vert mirrored packages.
This should fix it.
=> Bring hwraid packages into merged snapshot

aptly-snapshot-create.yml, aptly-snapshot-merge-and-publish.yml
We should use distro instead of components.
Components has the following issues:
- Adding a new component to a repo (like adding a new tag) automatically
claims the component is already published if there is no change and
not instructed to publish all the components (-components=,,)
- We cannot simply drop a component in place. We can switch it, but
then it involves more wiring in code for automation.
Using distros with "/" would be the best solution, but aptly doesn't
allow that. In the meantime, a new RPC release will be in the apt
repository in the form artifact_version-system_distribution.
Signed-off-by: Jean-Philippe Evrard <jean-philippe.evrard@rackspace.co.uk>
=> Rollback components usage

aptly-vars.yml
hwraid packages by le-vert.net have the same (architecture, name,
version) for package 3dm2.
This properly fails as it should.
Let's make this one independant to handle the problem of upstream
packaging.
=> Revert the addition of le-vert.net

aptly-vars.yml
We need both elasticsearch 1.7 and 2.x into our mirror for
upgrade reasons (reindexing using latest 1.7 version).
=> Add ES 2.x into our mirror.

build-python-artifacts.sh
This patch adds a script which executes the AIO configuration,
adjusts it to suit the artifact building process, then executes
the repo build.
Connects https://github.com/rcbops/u-suk-dev/issues/1020
=> Add python artifact build script

aptly-snapshot-merge-and-publish.yml, aptly-vars.yml
If 2 versions of a the same package for the same architecture in
different repos exist, the order of the merge applies and the merged
snapshot will only get the package (with its possible many versions)
from one repo.
We need this to have versions 1.7 and 2.x for elasticsearch at the same
time in the merged repo.
=> Add aptly snapshot merge flags

build-apt-artifacts.sh
Currently the apt building script is in jenkins-rpc.
While it seems more clear to define the job there, including the
script from the rpc-artifacts repo is more flexible.
=> Make the apt building script in tree

stage-python-artifacts.yml
This patch adds a utility playbook which will stage
all python artifacts for a given RPC release from
an upstream repository.
Connects https://github.com/rcbops/u-suk-dev/issues/766
=> Add git/python artifact staging playbook

stage-apt-artifacts-mirror.list.j2, stage-apt-artifacts.yml
This patch adds an apt artifacts staging playbook
which uses apt-mirror to execute a complete mirror
of the RPC-O apt artifacts.
Connects https://github.com/rcbops/u-suk-dev/issues/1112
=> Add apt staging playbook

apt/aptly-all.yml
In 6e6c3a2 the owner of the files when pulling was incorrectly
changed from the aptly_user to the webservice_owner. This results
in aptly not being able to operate on the database any more.
When setting owner/group to 'no' with the synchronise
module it passes the '--no-owner --no-group' parameters
to rsync which causes the '--chown' option to be ignored
and the ownership of the files to be set to the user
executing the rsync command (ie root). This results in
aptly not being able to operate on the database as the
files are owned by root instead of the aptly user.
When leaving the owner/group settings out of the module
settings no extra options are passed to rsync and '--chown'
works as expected.
=> RO-3117 Ensure that file ownership is correct

apt/aptly-all.yml, apt/aptly-install-and-mirror.yml
When synchronising the aptly database from rpc-repo
rsync changes the owner:group to root when it is only
modifying the attributes of the file instead of the
contents - at least I think that's the condition.
After spending several hours trying to figure out
how to do it better in the rsync options, and failing,
this patch opts to use a simpler change which just
forces the owner:group after the sync is completed.
Some line spaces are added into the playbook to improve
readability.
Issue: [RO-3117](https://rpc-openstack.atlassian.net/browse/RO-3117)
=> RO-3117 Fix issues with downloading aptly data from rpc-repo

apt/aptly-all.yml
When synchronising the aptly database to rpc-repo
rsync changes the owner:group to root when it is only
modifying the attributes of the file instead of the
contents - at least I think that's the condition.
After spending several hours trying to figure out
how to do it better in the rsync options, and failing,
this patch opts to use a simpler change which just
forces the owner:group after the sync is completed.
Included are the setting of --no-owner and --nogroup
when doing the pull. These are important to make it
behave correctly but are unfortunately not enough.
Issue: [RO-3117](https://rpc-openstack.atlassian.net/browse/RO-3117)
=> RO-3117 Force the correct owner on artifact files

apt/aptly-all.yml, apt/aptly-install-and-mirror.yml
When setting owner/group to 'no' with the synchronise
module it passes the '--no-owner --no-group' parameters
to rsync which causes the '--chown' option to be ignored
and the ownership of the files to be set to the user
executing the rsync command (ie root). This results in
aptly not being able to operate on the database as the
files are owned by root instead of the aptly user.
When leaving the owner/group settings out of the module
settings no extra options are passed to rsync and '--chown'
works as expected.
Also, as mentioned in [1], quoting the rsync_opts arguments
breaks the functionality. Thus the quotes have been removed.
This has been extensively validated to be a working
implementation for Ansible 2.3 onwards in [2].
[1] https://github.com/ansible/ansible/issues/23575
[2] …
=> RO-3117 Correct synchronize module usage

git/build-git-artifacts.sh
When the git artifact build wants to upload, the key
file path in the inventory is set to 'False' due to
the REPO_KEYFILE value not being present when the
inventory is prepared near the top of the script.
Given that the inventory is needed to run the initial
playbook, this patch just implements a rebuild of the
inventory if the right env vars are present just before
the upload is actioned.
=> RO-3146 Ensure inventory includes the key file

python/upload-python-artifacts.yml
As per the notes in [1] each argument has to be a
seperate item in the list and each one is quoted.
To ensure that the exclusion key word and the value
being applied are taken as a single argument, we
make sure there are no spaces between them.
[1] https://github.com/ansible/ansible/issues/23575
=> RO-3156 Correct synchronise module usage

python/build-python-artifacts.sh, setup/artifact-setup.sh
Currently, when building the python artifacts, the deployment implements
the Ubuntu updates, backports and UCA repositories alongside the rpco apt
artifacts repository. This pollutes the python artifacts with binaries
which are not available in the apt artifact repository which may ultimately
cause service failures when trying to use the python artifacts.
This also affects the container artifact builds as they end up using the
wrong repositories, resulting in builds which differ on every execution.
This patch implements a change to the install script to set the OSA AIO
bootstrap options to prevent it from re-implementing the extra sources.
The functions loading is slightly adjusted so that we can make use of
the OA_OVERRIDES environment variable for the overrides implemented
instead of …
=> RO-3284 Set AIO bootstrap options to ensure apt artifacts are used

setup/artifact-setup.sh
In some systems where jenkins executes the artifact
builds the /opt/rpc-openstack folder is a dead symlink
at the time this script runs. A dead symlink does not
show as a valid file using a file test, so the script
tries to reclone the git repo inappropriately.
=> RO-3284 Test for /opt/rpc-openstack differently

setup/artifact-setup.sh
In jenkins the folder the script is run from is not
/opt/rpc-openstack in all cases. To cater for this
situation we check whether the folder executed from
has 'rpc-openstack' in the name. If so, we symlink
it to /opt/rpc-openstack. If not, then we think that
rpc-openstack has not been cloned, so we clone it
and replace the submodule with the current directory.
=> RO-3284 Either symlink or clone rpc-openstack

apt/build-apt-artifacts.sh, containers/build-process.sh, python/build-python-artifacts.sh
Once RPC-O's configuration is implemented, ansible is
not available in a way that's useful to the artifact
builds. As such, we ensure that ansible is bootstrapped
appropriately before all artifact builds.
=> RO-3286 Bootstrap ansible with OSA for artifact builds

apt/build-apt-artifacts.sh, containers/build-process.sh, functions.sh, git/build-git-artifacts.sh, python/build-python-artifacts.sh, setup/artifact-setup.sh, user_rcbops_artifacts_building.yml
Instead of bootstrapping ansible in each build script
just do it in the artifact-setup script. Also clean
up some variable settings which do not need to be
done in bash as they're universal.
=> RO-3286 Clean up ansible bootstrapping

setup/artifact-setup.sh
If the current working directory the script is run
from is /opt/rpc-openstack, then we should not try
to symlink or clone to that location.
=> RO-3284 Correct rpc-openstack symlink condition

containers/build-process.sh, user_rcbops_artifacts_building.yml
To build the container artifacts, there is no pip.conf in order
to inform the installation process of the extra links needed to
access the python wheels needed for the installation. This is due
to the use of the tagfilter strategy which skips all -config tags
including the one which places the pip.conf file down.
Unfortunately we cannot use jinja in the strategy to use the config
tag for the default container artifact and not for the rest, so
instead we provide extra pip options here to cover what would be
in pip.conf.
=> RO-3263 Provide pip extra-links during artifact builds

containers/artifact-build-chroot.yml, containers/container-vars.yml
When consuming the images prepared with machinectl,
the current method causes machinectl to hang during
the decompression of the image and spikes the CPU
usage to 100%. This affects the RPC-O container
images, but does not happen with upstream images.
In reviewing the difference with how the compression
is done upstream [1], it uses the default compression
rather than our elevated compression and uses a far
simpler set of command-line options.
This patch changes our preparation of the compressed
container images to use the same command line options
for maximum compatibility.
Extra line breaks are added into the playbook in order
to improve readability.
[1] https://github.com/lxc/lxc-ci/blob/9706d80acb6dc2bd3ea519aed82b1b1940953120/bin/build-image#L166
=> RO-3316 Correct image compression method

containers/build-process.sh, git/build-git-artifacts.sh, python/build-python-artifacts.sh
Currently the functions to verify whether artifacts are
available or not are used prior to them being available,
causing unexpected results. This patch makes sure that
they are sourced before using them.
=> RE-1267 Source functions before using them

containers/build-process.sh, git/build-git-artifacts.sh, python/build-python-artifacts.sh, setup/artifact-setup.sh
Currently the checks run before a python package is installed
to run the script which figures out the rpc_release value. As
such we need to do the checks in the install script after the
installation of the python package, but before the preparation
of the artifact configuration.
This implementation simply disabled their use if they are not
available. As this is the default, it will only take effect if
the artifacts are not available and the artifact build script
intended to use them.
=> RE-1267 Correct existing artifact availability checks

containers/artifact-build-chroot.yml
Currently the artifacts are being compressed with the full
path of the original rootfs, rather than the relative path.
This patch changes the compression process to properly only
compress relative contents.
=> RO-3626 Ensure artifacts are compressed with correct path

apt/aptly-snapshot-create.yml
The current matching mechanism is very loose, and will remove
r16.0.0-alpha.1 when it means to only remove r16.0.0. This
patch improves the matching considerably to prevent that.
=> RE-1280 Be more specific when replacing pubs/snaps

apt/aptly-snapshot-create.yml
Currently 'slushie-r16.0.0-erlang-xenial' does not get
matched for the snapshot delete process when replacing
an existing snapshot. This is due to it missing the
extra '-' in the name required by the current regex.
=> RE-1280 Fix regex match for non-merged snapshot

apt/aptly-vars.yml
To ensure that the UCA packages for pike use the right
UCA packages, the Pike UCA repo is added for mirroring
and the r16 merged snapshot is updated to use it.
Additional line breaks are added between all the mirrors
to make them easier to read.
=> RO-3685 Update UCA to include Pike and r16 to use it

containers/artifact-build-chroot.yml
Currently due to a poor regex match, the index items for
content such as [1] are being replaced when trying to add
[2]. This patch adds the appropriate delimiter to prevent
this from happening.
[1] ubuntu;xenial;amd64;rsyslog_server-r16.0.0-beta.1;...
[2] ubuntu;xenial;amd64;rsyslog_server-r16.0.0;...
=> RO-3777 Prevent unintended LXC index data loss
